name: Deploy Backend to OCI VM

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only run this workflow if changes are made to the backend folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Source Code to OCI VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "backend/"
          target: "/home/${{ secrets.OCI_USERNAME }}/ims_backend"
          strip_components: 1

      - name: Compile and Restart Backend on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.OCI_USERNAME }}/ims_backend
            export PATH="$PATH:/usr/lib/dart/bin"
            dart pub get
            dart compile exe bin/server.dart -o ims_server
            sudo systemctl restart ims_backend.service
